Tidy up repository
catalyst-ci-cd/catalyst pull request #18
Opened 2023-12-08 12:27 UTC by KhaledHegazy222

## Tidy up repository

### Changes Made:

1. **README Updates:**
   - Updated the main README file with essential project information.
   - Added a separate README in the `docs` directory for detailed documentation.

2. **License:**
   - Included the MIT License file (`LICENSE`) to specify project licensing.

3. **Makefile:**
   - Introduced a Makefile to streamline common development tasks.

4. **Issue and PR Templates:**
   - Added templates for creating issues and pull requests to standardize contributions.

2023-12-13 13:35 UTC, tareknaser requested changes
Thank you for your efforts. I left some comments but I believe we're almost there. 

Given that Catalyst is currently under development, I suggest keeping the README file simple without detailed information on "getting started" and "features" for now. Let's keep it minimal. 
Additionally, we can include a "Development Status" section that directs users to our current milestone for more information.

2023-12-13 13:35 UTC, tareknaser commented on Makefile
Let's remove this file

2023-12-13 13:35 UTC, tareknaser commented on docs/contribution.md
> +Include any instructions needed for setting up the development environment. This could include dependencies, environment variables, or other prerequisites.
It appears that you copied the template without making any edits to tailor it to Catalyst.

2023-12-13 13:35 UTC, tareknaser commented on README.md
> +- **Scheduler** to manage jobs execution order
We don't necessarily need to detail the project structure in our README file. This information can be better suited for the contribution page or a separate documentation file.

2023-12-13 13:35 UTC, tareknaser commented on README.md
> +   ```
Executing `./catalyst` currently has no effect. 
Since the project is not yet ready for use, we won't include a "Getting Started" section at this point.

2023-12-13 13:35 UTC, tareknaser commented on README.md
> +## Features
```suggestion
```

2023-12-13 13:35 UTC, tareknaser commented on .github/workflows/ISSUE_TEMPLATE/bug_report.md
> +OS: [e.g. iOS]
```suggestion
OS: [e.g. Linux/Windows]
```

2023-12-13 13:35 UTC, tareknaser commented on README.md
> +Catalyst is a powerful CI/CD (Continuous Integration/Continuous Deployment) tool designed to streamline workflows. This tool empowers developers and DevOps teams to efficiently manage and automate th
```suggestion
Catalyst is an ambitious CI/CD (Continuous Integration/Continuous Deployment) tool currently in active development. Our goal is to create a powerful tool that streamlines workflows, empowering developers and DevOps teams to efficiently manage and automate the software development lifecycle, from code integration to deployment.

> Please note that the project is still under development and not yet ready for production use.
```
```

2023-12-14 09:19 UTC, AbdelrahmanElawady requested changes

2023-12-14 09:19 UTC, AbdelrahmanElawady commented on docs/contribution.md
> +- **Scheduler** to manage jobs execution order
overview of the project doesn't go in the contribution guide

2023-12-14 09:19 UTC, AbdelrahmanElawady commented on docs/contribution.md
> +Include any instructions needed for setting up the development environment. This could include dependencies, environment variables, or other prerequisites.
I am not sure I understand what is this

2023-12-14 09:19 UTC, AbdelrahmanElawady commented on .github/pull_request_template.md
> +
I don't think we need screenshot section

2023-12-14 09:25 UTC, KhaledHegazy222 commented on docs/contribution.md
> +- **Scheduler** to manage jobs execution order
should I remove it or I just need to move it somewhere else ?

2023-12-14 09:26 UTC, AbdelrahmanElawady commented on docs/contribution.md
> +- **Scheduler** to manage jobs execution order
I would say remove it until we actually have something working to document

2023-12-14 09:49 UTC, AbdelrahmanElawady approved these changes

2023-12-14 10:11 UTC, tareknaser approved these changes

2023-12-14 13:44 UTC, merged