20 add authentication
catalyst-ci-cd/catalyst pull request #26
Opened 2023-12-14 16:25 UTC by MahmoudShakour

add login and signup endpoints

2023-12-15 12:30 UTC, AbdelrahmanElawady requested changes
Nice Work!

2023-12-15 12:30 UTC, AbdelrahmanElawady commented on db/auth_service.go
> +func (d *DBClient) GetUserByEmail(email string) (User, error) {
all public methods should be documented

2023-12-15 12:30 UTC, AbdelrahmanElawady commented on db/auth_service.go
> +func (d *DBClient) GetUserByUserName(userName string) (User, error) {
it's `username`. just one word

2023-12-15 12:30 UTC, AbdelrahmanElawady commented on db/auth_service.go
> +func (d *DBClient) CreateUser(username, email, password string) (User, error) {
hmm should it take all fields as arguments or just one User struct that contains all the data?

2023-12-15 12:30 UTC, AbdelrahmanElawady commented on db/db_client.go
> +var dbClient DBClient
this is not used anywhere

2023-12-15 12:30 UTC, AbdelrahmanElawady commented on db/db_client.go
> +	}
what is the point of this function? the caller of NewDBClient should have the client object.

2023-12-15 12:30 UTC, AbdelrahmanElawady commented on db/db_client.go
> +	}
also there is multiple issues with this function.
- config is hardcoded so no way to change the file
- db has access to other config which it shouldn't
- errors should be returned not printed unless if it can't be handled it should be logged properly

2023-12-15 12:30 UTC, AbdelrahmanElawady commented on docker-compose.yml
why do we have docker-compose with just postgres in it?

2023-12-15 12:30 UTC, AbdelrahmanElawady commented on db/models.go
> +type User struct {
public structs should be documented

2023-12-15 12:30 UTC, AbdelrahmanElawady commented on main.go
> +
all of that should be in the cmd/ directory with the proper starting command

2023-12-15 12:30 UTC, AbdelrahmanElawady commented on main.go
> +	config, err := config.LoadConfig("config.json")
config path should be parsed from flags not hardcoded. Check [cobra](https://github.com/spf13/cobra) for details

2023-12-15 12:30 UTC, AbdelrahmanElawady commented on server/server.go
> +	router.POST("/login", s.LogIn)
shouldn't there be an endpoint for verifying the registration?

2023-12-15 12:30 UTC, AbdelrahmanElawady commented on server/users_controllers.go
> +	Email    string `binding:"required,email"`
I am not familiar with gin but what is the email binding tag does here?

2023-12-15 12:30 UTC, AbdelrahmanElawady commented on server/users_controllers.go
> +	if _, err := db.GetUserByEmail(signUpRequestBody.Email); err != gorm.ErrRecordNotFound {
other errors are not handled. check the rest too

2023-12-15 12:30 UTC, AbdelrahmanElawady commented on server/users_controllers.go
> +			"message": err,
500 error codes should have a generic error message (like the constant you set in the start of the file) not the actual errors as used shouldn't know what happened internally

2023-12-15 12:30 UTC, AbdelrahmanElawady commented on server/users_controllers.go
> +var LogInRequestBody struct {
I am not sure this needs to be public

2023-12-15 12:30 UTC, AbdelrahmanElawady commented on server/users_controllers.go
> +func (s *Server) LogIn(ctx *gin.Context) {
Login and Signup not LogIn and SignUp

2023-12-15 21:10 UTC, MarwanRadwan7 requested changes

2023-12-15 21:10 UTC, MarwanRadwan7 commented on server/users_controllers.go
> +	Email    string `binding:"required,email"`
You need to specify `json:` here for better naming convention of json in request body

2023-12-15 21:10 UTC, MarwanRadwan7 commented on server/users_controllers.go
> +	Email    string `binding:"required,email"`
same here.

2023-12-16 09:37 UTC, MarwanRadwan7 requested changes

2023-12-16 09:37 UTC, MarwanRadwan7 commented on server/server.go
> +	router.POST("/login", s.LogIn)
Add `/api/v1` for a better practice

2023-12-16 09:40 UTC, MarwanRadwan7 commented on server/server.go
> +	router.POST("/login", s.LogIn)
You can also use `Group("/user")` to combine all routes related to the user together. [Group](https://gin-gonic.com/docs/examples/grouping-routes/)

2023-12-16 10:21 UTC, MarwanRadwan7 requested changes

2023-12-16 10:21 UTC, MarwanRadwan7 commented on server/users_controllers_test.go
> +package server
use `server_test`

2023-12-18 00:04 UTC, MahmoudShakour commented on server/users_controllers.go
> +	Email    string `binding:"required,email"`
to make sure that the field satisfies email format

2023-12-18 00:09 UTC, MahmoudShakour commented on server/users_controllers_test.go
> +package server
but i use private methods in server package

2023-12-18 07:44 UTC, Omar622 requested changes
nice work, tiny comments

2023-12-18 07:44 UTC, Omar622 commented on cmd/server_command.go
> +			os.Exit(1)
you may use log.Fatal

2023-12-18 07:44 UTC, Omar622 commented on db/db_client.go
> +	return err
no need for defining err variable, return the AutoMigrate result directly

2023-12-18 07:44 UTC, Omar622 commented on internal/auth_utility.go
> +func HashPassword(userPassword string) (string, error) {
function docs should start with the function name i.e. // HashPassword converts ...
please, check all.

2023-12-18 07:44 UTC, Omar622 commented on server/server.go
> +	authGroup:=router.Group("api/v1/users")
the api version is a variable in config, use it.

2023-12-18 08:10 UTC, Omar622 commented on db/auth_service.go
> +		return User{}, DuplicateEmailErr
i think it's better to return the error directly and check the type of error in the endpoint handler.

2023-12-18 14:50 UTC, MarwanRadwan7 commented on server/users_controllers_test.go
> +package server
Tbh I see no problem if we turned them into public methods

2023-12-19 19:52 UTC, MahmoudShakour commented on server/users_controllers_test.go
> +package server
lgtm

2023-12-20 06:10 UTC, Omar622 approved these changes
nice work

2023-12-20 17:13 UTC, MarwanRadwan7 approved these changes

2023-12-20 20:12 UTC, AbdelrahmanElawady approved these changes

2023-12-20 20:19 UTC, merged