Implement YAML Parsing in `catalyst-parser` Package
catalyst-ci-cd/catalyst pull request #9
Opened 2023-11-02 15:55 UTC by tareknaser

## Description
This pull request introduces the `catalyst-parser` package to parse YAML configuration files. 
The `ParseWorkflowConfig` function reads the specified YAML file and extracts the workflow name, trigger type, and value, as well as job configurations. It then constructs a `WorkflowConfig` instance and returns it.

Closes #3

## How Is This Tested?
Added 3 test cases in the `catalyst-parser` package under the `internal/catalyst-parser/catalyst-parser_test.go` file. 
Tests cover various scenarios, including different script structures and unsupported trigger types.

2023-11-08 19:48 UTC, KhaledHegazy222 requested changes

2023-11-08 19:48 UTC, KhaledHegazy222 commented on internal/catalyst-parser/catalyst-parser_test.go
> +	return os.WriteFile(filename, []byte(content), 0644)
I think it would be more readable if your named the permission mode with a readable name instead of passing it directly.

2023-11-08 19:48 UTC, KhaledHegazy222 commented on internal/catalyst-parser/types.go
> +func (wc WorkflowConfig) Equal(other WorkflowConfig) bool {
I think passing struct as a pointer would be better instead of passing a copy of the struct. for example in large workflows with large scripts and jobs this may be an issue later with the performance. what do you think ?

2023-11-09 18:26 UTC, tareknaser commented on internal/catalyst-parser/catalyst-parser_test.go
> +	if !expected.Equal(*workflow) {
good point

2023-11-09 18:29 UTC, tareknaser commented on internal/catalyst-parser/example-workflow.yaml
I've moved the example YAML file to the `docs/` directory for now.
We should consider the structure and content of our documentation.

2023-11-09 18:29 UTC, tareknaser commented on internal/catalyst-parser/parser.go
> +	"gopkg.in/yaml.v2"
good catch

2023-11-09 18:30 UTC, tareknaser commented on internal/catalyst-parser/catalyst-parser_test.go
> +	return os.WriteFile(filename, []byte(content), 0644)
Good catch

2023-11-10 19:38 UTC, AbdelrahmanElawady commented on internal/parser/parser.go
> +func (p *Parser) ParseWorkflowConfig(filename string) (*WorkflowConfig, error) {
Isn't the input a string of the file content?

2023-11-11 10:45 UTC, KhaledHegazy222 approved these changes

2023-11-11 12:52 UTC, tareknaser commented on internal/parser/parser.go
> +func (p *Parser) ParseWorkflowConfig(filename string) (*WorkflowConfig, error) {
No, it takes a filename

2023-11-11 12:56 UTC, AbdelrahmanElawady commented on internal/parser/parser.go
> +func (p *Parser) ParseWorkflowConfig(filename string) (*WorkflowConfig, error) {
Hmm what file would that be? I assumed the server would receive the content and pass it to the parser, right?

2023-11-11 13:00 UTC, tareknaser commented on internal/parser/parser.go
> +func (p *Parser) ParseWorkflowConfig(filename string) (*WorkflowConfig, error) {
I figured that would be the local file but this doesn't make much sense on the long run 
this needs to accept the file content instead

2023-12-07 15:41 UTC, AbdelrahmanElawady approved these changes
Looks Good

2023-12-08 08:15 UTC, KhaledHegazy222 approved these changes
great job, thank you

2023-12-08 09:04 UTC, merged